/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.nhatvu148.kafka;

import static java.lang.System.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        out.println(new App().getGreeting());
        
        // OrderProducer.Run();
        OrderConsumer.Run();
    }
}
